# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/stfwi/wilescollection/issues/"
license="MIT"

[[mods]]
modId="wilescollection"
version="${file.jarVersion}"
displayName="WilE's Collection"
description="Adds a small bunch of decoration and functionality to vanilla styled packs."
authors="wilechaote"
#credits="The Forge Smiths."
updateJSONURL="https://raw.githubusercontent.com/stfwi/wilescollection/1.16/meta/update.json"
displayURL="https://github.com/stfwi/wilescollection/"
logoFile="logo.png"

[[dependencies.wilescollection]]
  modId="forge"
  mandatory=true
  versionRange="[36.2.0,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.wilescollection]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.5,)"
  ordering="NONE"
  side="BOTH"
