# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://github.com/stfwi/wilescollection/issues/"
license="MIT"

[[mods]]
modId="wilescollection"
version="${file.jarVersion}"
displayName="WilE's Collection"
description="Adds a small bunch of decoration and functionality to vanilla styled packs."
authors="wilechaote"
#credits="The Forge Smiths."
updateJSONURL="https://raw.githubusercontent.com/stfwi/wilescollection/versions/1.19.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wiles-collection"
logoFile="logo.png"

[[dependencies.wilescollection]]
  modId="forge"
  mandatory=true
  versionRange="[42.0.1,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.wilescollection]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.19.1]"
  ordering="NONE"
  side="BOTH"
